build: fix linking with some linkers
/usr/bin/ld: gui/gui_one_video_gui-ovg-main.o: undefined reference to symbol 'g_module_symbol'
//usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0: error adding symbols: DSO missing from command line